openapi: 3.0.0
info:
  title: Needle In A Haystack
  version: '1.0'
  description: |-
    This API has a method called findNeedles() that searches though a sentence String called a "haystack" and lookes for specified keywords called "needles" and outputs a count of how times each of those keywords appear in that sentence.

    Here is the Java Method:

    ```java
    public static void findNeedles(String haystack, String[] needles) {
        if (needles.length > 5) {
            System.err.println("Too many words!");
        } else {
            int[] countArray = new int[needles.length];
            for (int i = 0; i < needles.length; i++) {
                String[] words = haystack.split("[ \"\'\t\n\b\f\r]", 0);

                //Check for a comma at the end of a String element in array words and 
                //remove that Character from that String element.
                for (int wc = 0; wc < words.length; wc++) {
                    if(words[wc].contains(",")){
                        //Remove that comma at the end.
                        words[wc] = words[wc].substring(0, words[wc].length() -1);
                    }
                    else {
                        //do nothing
                    }
                }

                //Check for a period at the end of a String element in array words and 
                //remove that Character from that String element.
                for (int wp = 0; wp < words.length; wp++) {
                    if(words[wp].contains(".")){
                        //Remove that period at the end.
                        words[wp] = words[wp].substring(0, words[wp].length() -1);
                    }
                    else {
                        //do nothing
                    }
                }

                for (int j = 0; j < words.length; j++) {
                    if (words[j].compareToIgnoreCase(needles[i]) == 0) {
                        countArray[i]++;
                    }
                }
            }
            for (int j = 0; j < needles.length; j++) {
                System.out.println(needles[j] + ": " + countArray[j]);
            }
        }
    }
    ```
servers:
  - url: 'http://dusenbery.dev/apis/needleinahaystack'
    description: stage
paths:
  '/needleCount/{haystack}/{needles}':
    get:
      summary: Needle Count
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                description: Returns an Array of Strings listing off how many of each needle keywords were found.
                items:
                  type: string
                  example: '{"pizza: 2",  "wine: 1",  "BBQ: 1",  "bourbon: 1"}'
              examples:
                Example Output:
                  value:
                    - '{"pizza: 2",  "wine: 1",  "BBQ: 1",  "bourbon: 1"}'
            application/xml:
              schema:
                type: array
                description: Each element of the Array is a String representing the count of how many of each needle keyword found in the haystack of a sentence.
                items:
                  type: string
          headers:
            haystack:
              schema:
                type: string
                example: Let's find a needle and thread and another thread.
              description: A sentence in English language.
            needles:
              schema:
                type: array
                example: '{"needle", "thread"}'
              description: An array of Strings to look for.
      operationId: get-needleCount
      description: 'Takes in a String that should be formatted as a sentence in English and an Array of keyword Stings to look for in the sentence. Returns a count of those keywords. '
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type:
                - string
                - array
              example: 'I went to Chicago and ate some pizza, then later that month flew to Napa and drank some wine. After that, I drove down to Texas and ate some BBQ. I couldn''t get enough American cuisine, and had to drive over to Kentucky to taste some Bourbon. Even after all this, I still want to have more pizza, and try it in New York.'
              enum:
                - string
              items:
                type: string
                example: '{"pizza", "wine", "BBQ", "bourbon"'
            examples: {}
          application/xml:
            schema:
              type: object
              properties:
                '':
                  type: array
                  description: ''
                  items:
                    type: string
                    example: '{"pizza", "wine", "BBQ", "bourbon"}'
              required:
                - ''
        description: Example request
    parameters:
      - schema:
          type: string
        name: haystack
        in: path
        required: true
        description: A sentence in English language.
      - schema:
          type: array
        name: needles
        in: path
        required: true
        description: An array of Strings to look for.
components:
  schemas: {}
